# Generated by Django 4.2.3 on 2023-07-26 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(blank=True, null=True)),
                ('importance', models.PositiveIntegerField(blank=True, default=0)),
                ('category', models.CharField(choices=[('WO', 'Work'), ('HO', 'Home'), ('FA', 'Family'), ('FR', 'Friends'), ('HB', 'Hobby'), ('GE', 'General')], default='GE', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited_last', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table_comment': 'Table created by Django',
                'ordering': ['-edited_last'],
            },
        ),
    ]
